package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/hypr/?.lua"

hl.config({ autogenerated = false })

local prog      = require("lua.programs")
local autostart = require("lua.autostart")
local keybinds  = require("lua.keybinds")
local screen    = require("lua.Monitor")

require("lua.environment")
require("lua.appearance")
require("lua.inputs")

autostart.load(prog.terminal)
keybinds.setup(prog)

hl.window_rule({
    name           = "suppress-maximize-events",
    match          = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = { 
        class    = "^$", 
        title    = "^$", 
        xwayland = true, 
        float    = true 
    },
    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})